model_context_window = 1000000
model_auto_compact_token_limit = 900000
model_reasoning_effort = "medium"

base_url = "http://127.0.0.1:15721/v1"

notify = ["/Users/xiaoguodelaoguo/.hermes/profiles/im-genius/home/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[mcp_servers]
[marketplaces.openai-primary-runtime]
last_updated = "2026-05-12T07:10:23Z"
source_type = "local"
source = "/Users/xiaoguodelaoguo/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.openai-bundled]
last_updated = "2026-06-04T07:42:31Z"
source_type = "local"
source = "/Users/xiaoguodelaoguo/.codex/.tmp/bundled-marketplaces/openai-bundled"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/xiaoguodelaoguo/.codex"
CODEX_HOME = "/Users/xiaoguodelaoguo/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "4b6bfaf4ed2ce9b5cd68e60a61642eb4927a36306ba8c8993f6058607b3530fb"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."browser-use@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[features]
memories = true
js_repl = false

[memories]
generate_memories = true
use_memories = true

[projects."/Users/xiaoguodelaoguo/Documents/Codex/2026-05-12/new-chat"]
trust_level = "trusted"

[projects."/Users/xiaoguodelaoguo/Documents/Codex/2026-05-12/new-chat-2"]
trust_level = "trusted"

[projects."/Users/xiaoguodelaoguo/Documents/Codex/2026-05-12/hello"]
trust_level = "trusted"

[projects."/Users/xiaoguodelaoguo"]
trust_level = "trusted"

[projects."/Users/xiaoguodelaoguo/Golden Project"]
trust_level = "trusted"

[projects."/private/tmp"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
